export const questions = [
  { q: "Which is the safest way to accept a payment from a stranger?", options: ["Share your UPI ID only", "Share your UPI PIN", "Open their link", "Scan their QR code"], answer: 0, why: "To receive money, share your UPI ID or QR. Never enter your PIN or scan a QR to receive money." },
  { q: "What does compounding mean?", options: ["Losing money over time", "Earning interest on interest", "Paying a one-time fee", "Dividing money into parts"], answer: 1, why: "Your returns can also earn returns, which can grow savings over time." },
  { q: "Which is a need rather than a want?", options: ["A new console", "Basic groceries", "Designer sneakers", "Movie tickets"], answer: 1, why: "Food is an essential need. The other choices are wants." },
  { q: "What should you do with a suspicious KYC link?", options: ["Open it", "Forward it", "Delete it and contact your bank directly", "Reply with details"], answer: 2, why: "Urgent unknown links can be phishing. Use your bank’s official app or a trusted number." },
  { q: "What is a budget?", options: ["A plan for income and expenses", "A bank account", "A way to spend everything", "A type of loan"], answer: 0, why: "A budget plans how income will be used before it is spent." }
];
export const terms = [
  ["Inflation", "When prices rise over time and each rupee buys a little less."], ["Dividend", "A share of a company’s profits paid to its shareholders."], ["Asset", "Something you own that has value."], ["Liability", "Something you owe, such as a loan."], ["Net worth", "The value of what you own minus what you owe."], ["Interest", "The cost of borrowing or the return earned on savings."], ["Diversification", "Spreading investments across different types to reduce reliance on one."], ["Compound interest", "Interest calculated on both the original amount and earlier interest."]
].map(([term, meaning]) => ({ term, meaning }));
export const lessons = [
  { title: "Budgeting 101", category: "Money basics", time: "5 min", sections: [["What is a budget?", "A budget is a plan for your money. Decide how much to use for different things before the month starts."], ["The 50/30/20 idea", "One starting point is 50% for needs, 30% for wants and 20% for saving. Adjust it to fit your real situation."], ["How to begin", "Write down income, list expenses, then decide what you want to save first."]] },
  { title: "Saving & interest", category: "Money basics", time: "4 min", sections: [["Small steps add up", "Saving a little regularly can be easier to maintain than waiting for a large amount."], ["Compound growth", "Compounding lets earlier returns earn returns too. Growth is not guaranteed, especially for investments."], ["Emergency savings", "A reserve can help with unexpected costs without disrupting your whole plan."]] },
  { title: "Spotting online scams", category: "Digital safety", time: "4 min", sections: [["Pause at urgency", "Scams often pressure you to act immediately or keep a secret."], ["Protect your PIN and OTP", "Never share a UPI PIN or one-time password. A real payment receipt appears in your own app."], ["Verify independently", "Contact the person or bank through a number or app you already trust."]] },
  { title: "Investing and risk", category: "Investing", time: "6 min", sections: [["Return and risk", "Investments can rise or fall in value. Higher possible returns usually come with greater risk."], ["Spread your risk", "Diversifying means not relying on one company or asset. It cannot remove all risk."], ["Think long term", "Match a choice to when you may need the money and learn before making real decisions."]] }
];
export const scenarios = [
  { category: "Digital safety", text: "A friend messages asking for ₹2,000 urgently. The account looks familiar, but the request is unusual.", choices: ["Send it right away", "Call using a number you already know", "Share your UPI PIN"], answer: 1, why: "A familiar profile can be impersonated. Verify urgent requests separately and never share your PIN." },
  { category: "Spending", text: "Headphones you do not need are 40% off for one hour. What is a useful next step?", choices: ["Buy before the deal ends", "Check your budget and wait a day", "Borrow so you do not miss it"], answer: 1, why: "A discount only saves money when the purchase fits your plan. Waiting can help avoid impulse spending." },
  { category: "Banking", text: "A text says your account will be blocked unless you follow a KYC link.", choices: ["Enter details in the link", "Use the bank’s official app or trusted number", "Reply with your OTP"], answer: 1, why: "Urgency and unknown links are common phishing signals. Never share your OTP or PIN." },
  { category: "Investing", text: "A simulated share falls after a headline. What is thoughtful?", choices: ["Put all savings into it", "Review risk and diversification", "Assume it will recover"], answer: 1, why: "Prices can fall and recovery is never guaranteed. Consider risk and time horizon." }
];
export const assets = [
  { id: "index", name: "India 50 Index", kind: "Index", base: 18500 }, { id: "tech", name: "Titan Tech", kind: "Stock", base: 2450 }, { id: "green", name: "Green Energy", kind: "Stock", base: 840 }, { id: "gold", name: "SafeGold", kind: "Commodity", base: 5200 }, { id: "fmcg", name: "Everyday FMCG", kind: "Stock", base: 1100 }, { id: "bank", name: "National Bank", kind: "Stock", base: 1550 }
];
export const missions = ["Complete a money quiz", "Record an expense", "Save toward a goal"];
export const avatars = [{ id: "rocket", name: "The Explorer", emoji: "🚀" }, { id: "bull", name: "The Patient Planner", emoji: "🐂" }, { id: "bear", name: "The Careful Checker", emoji: "🐻" }, { id: "piggy", name: "The Saver", emoji: "🐷" }];
